// src/utils/documentEmailBuilder.js

/**
 * Build email subject + HTML body for a given document type.
 * You can extend this switch with more document types later.
 *
 * @param {string} docTypeCode
 * @param {Object} employee   - Sequelize plain object or model instance
 * @param {Object} data       - templateData used for PDF (contains Month, NET_SALARY, etc.)
 *
 * @returns {{subject: string, html: string} | null}
 */
export function buildDocumentEmail(docTypeCode, employee, data = {}) {
    const code = (docTypeCode || '').toUpperCase();
    const empName = employee.empName || 'Team Member';

    // Common fields that might be useful
    const netSalary = data.NET_SALARY || '';
    const monthYear =
        data.EMAIL_MONTH_YEAR || // we will set this in SALARY_SLIP branch in controller
        data.Month ||
        '';

    switch (code) {
        // 🔹 Salary Slip email content
        case 'SALARY_SLIP': {
            const subject = monthYear
                ? `Salary Slip for ${monthYear} - ${empName}`
                : `Salary Slip - ${empName}`;

            const html = `
        <p>Dear ${empName},</p>

        <p>
          Please find attached your salary slip for
          <strong>${monthYear || 'the selected month'}</strong>.
        </p>

        ${netSalary
                    ? `<p>Your net pay for this month is <strong>₹${netSalary}</strong> (as per the attached salary slip).</p>`
                    : ''
                }

        <p>
          This slip summarises your earnings, deductions and net pay for the month.
          We recommend you keep this email and the attached salary slip for your
          personal records and any future reference.
        </p>

        <p>
          If you notice any discrepancy or have questions regarding your salary
          structure, deductions (PF/ESI/TDS) or reimbursements, please reply to
          this email or raise a ticket with the HR / Payroll team.
        </p>

        <p>
          Regards,<br/>
          HR &amp; Payroll Team<br/>
          Seecog Softwares Pvt. Ltd.
        </p>

        <hr style="border:none;border-top:1px solid #ddd;margin:16px 0;" />

        <p style="font-size:12px;color:#666;">
          <strong>Note:</strong> This is a system-generated email for sharing your
          monthly salary slip. If you have already received this slip from another
          channel, you can ignore this message.
        </p>
      `;

            return { subject, html };
        }

        // 🔹 Offer Letter email content (example)
        case 'OFFER_LETTER': {
            const subject = `Offer Letter - ${empName}`;

            const html = `
        <p>Dear ${empName},</p>

        <p>
          Congratulations! We are pleased to offer you the position of
          <strong>${data.DESIGNATION || data.designation || ''}</strong>
          at <strong>Seecog Softwares Pvt. Ltd.</strong>.
        </p>

        <p>
          Please find attached your detailed Offer Letter, which outlines
          your compensation, benefits and other terms &amp; conditions.
        </p>

        <p>
          Kindly review the attached document carefully. If you agree with the
          terms, please sign and share a scanned copy or respond to this email
          with your acceptance.
        </p>

        <p>
          If you have any questions, feel free to reply to this email.
        </p>

        <p>
          Regards,<br/>
          HR Team<br/>
          Seecog Softwares Pvt. Ltd.
        </p>
      `;

            return { subject, html };
        }

        // 🔹 Generic fallback for other letters
        default: {
            const subject = `${docTypeCode || 'Document'} - ${empName}`;

            const html = `
        <p>Dear ${empName},</p>

        <p>
          Please find attached your <strong>${data.documentName || docTypeCode}</strong>
          document generated by our HR system.
        </p>

        <p>
          If you have any questions or find any discrepancy, please contact
          the HR team.
        </p>

        <p>
          Regards,<br/>
          HR Team<br/>
          Seecog Softwares Pvt. Ltd.
        </p>
      `;

            return { subject, html };
        }
    }
}
